### PR TITLE
Yarn

### PR DESCRIPTION
**Pull request by sedubois**
This attempts to use the new yarn package manager. There was an issue with the `sharp` dependency, so took the liberty to upgrade it too, but there's still an issue.

Some OS X users may need to `brew uninstall vips` because of [this](https://github.com/lovell/sharp/issues/602).

- [x] fix [sharp issue](https://github.com/lovell/sharp/issues/606)

### CODE REVIEW

**Comment by lovell** [comment]
Please see https://github.com/yarnpkg/yarn/issues/872 for what is probably the underlying problem.

**Comment by bruno12mota** [comment]
This would be awesome! 👍

**Comment by sedubois** [comment]
Seems to work now!

**Comment by bruno12mota** [comment]
Awesome 👍

**Pull request merged**
