### PR TITLE
Hearsid reducer tests - Approx half reducers covered

### PR DESCRIPTION
**Pull request by hearsid**
Menu reducer is partially done, it can't be used full reference right now.

### CODE REVIEW

**Comment by bruno12mota** [comment]
Hey @hearsid! awesome PR, the build is broken for PRs I think. Just one question, why did you add the 'no-unused-expressions' rule? Other than that is ready to go :)

**Comment by hearsid** [comment]
@bruno12mota , no-unused-expressions rule was added to the __tests__ folder so that the chai expressions that don't return anything or call a function don't give as ESLint error. eg. 
`expect(someReducer(state, action)).to.be.true;`
will give a ESLint error, the solution was to add the required to the ESLint configuration file in the test folder.

**Comment by bruno12mota** [comment]
Oh ok, makes sense. We could use https://github.com/prodatakey/dirty-chai but not necessary. Can you just make it a valid json file?

```json
"rules": {
  "no-unused-expressions" : 0
}
```

with the double quotes and correct identation. after this it's ready to go 😃

**Comment by bruno12mota** [comment]
Awesome mate 👍

**Comment by hearsid** [comment]
@bruno12mota , Thank you :) .
I looked for other alternates when I added, 
```
"rules": {
  "no-unused-expressions" : 0
}
``` 
the best one was not to use 
`expect(...).to.be.true`
to be replaced by
`expect(...).to.equal(true)`
and so on. But adding the no unused expressions seemed to be the best option, so I went ahead with it.

**Comment by bruno12mota** [comment]
You did good, one less dependency and less points of possible failure

**Pull request merged**
