### PR TITLE
Remove deprecated React.PropTypes in favor of prop-types

### PR DESCRIPTION
**Pull request by iamclaytonray**
An incredibly simple PR, I admit. Instead of using React.PropTypes, I changed everything to prop-types. I didn't update React but here are the <a href='https://facebook.github.io/react/docs/typechecking-with-proptypes.html'>relevant docs from them.</a>

```
import React from 'react';
import PropTypes from 'prop-types';
```

Instead of:

`import React, {PropTypes} from 'react';`

### CODE REVIEW

**Comment by iamclaytonray** [comment]
I just noticed the build failed with Travis. I'll go ahead and make the changes and loop it back in.

**Comment by bruno12mota** [comment]
Hey @iamclaytonray thanks for the PR, it's still outputting some eslint errors, if you can fix those I'll gladly accept this 😄

**Comment by iamclaytonray** [comment]
Cool. I went ahead and removed those imports. Hopefully it builds with no errors this time!

**Comment by bruno12mota** [comment]
Nice, thanks! 👍

**Pull request merged**
