### PR TITLE
#250 replace Q with bluebird

### PR DESCRIPTION
**Pull request by andyhu**

### CODE REVIEW

**Comment by magalhas** [comment]
So you just changed the dependency?

**Comment by andyhu** [comment]
How about now? The code is much cleaner with bluebird. I also fixed .eslintrc config file since it's not valid

**Comment by andyhu** [comment]
Also we should ditch the outdated `superagent` for `axios` to make it more futuristic and with better promise/es7 support

**Comment by bruno12mota** [comment]
Hey @andyhu seems like your commits don't have a valid user as author. Make sure you config your settings:

```bash
git config --global user.email <your-email>
```

Otherwise your contributions won't show up.

Cheers

**Comment by andyhu** [comment]
Hi @bruno12mota,
Thanks for your comment, I set it to an anonymous user accidentally before. I'm ok with not showing the contribution but hopefully it doesn't mess things up in the repo.
Thanks for making this awesome project, keep your great work!

Cheers

**Comment by andyhu** [comment]
By there way, is there a unit test or something? I can't test if my PR works or not..

**Comment by bruno12mota** [comment]
Hey @andyhu thanks so much for contributing and the kind words! We do need help in the tests department, we still didn't start doing them since we've been re factoring relax quite a lot, but it's stable now so tests can start to be made. Actually made a tests build configuration some days ago and an example on how they should be done: https://github.com/relax/relax/tree/master/lib/shared/reducers/__tests__

If you could develop some tests at least for these changes would be awesome! 😃

**Pull request merged**
