### PR TITLE
User additions

### PR DESCRIPTION
**Pull request by Metevier**
I haven't had as much time as I'd like to work on this, but this fixes a bug which causes the server (it is currently happening even when creating a user from the init page) to crash when adding a user, and also adds basic user creation from the admin page.

### CODE REVIEW

**Comment by bruno12mota** [comment]
Awesome @Metevier! Thanks for contributing. On a side note we're using Relate, with which you can build mutations that will add or change nodes where it is being used: http://relax.github.io/relate/mutations.html

Still in the process of converting most of the actions to use it. Anyway great contribution! :wink:

**Comment by bruno12mota** [comment]
Check https://github.com/relax/relax/commit/8b218b9d262ac3eecb6a08fae05cf3348351e16e to see what I mean. This way the user is added to the list after being created

**Comment by Metevier** [comment]
Oh okay thats really cool, I was wondering how to get that to work. I plan to contribute more over the summer, that will definitely speed things up.

**Comment by bruno12mota** [comment]
That would be awesome :smile:

**Pull request merged**
